/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patmob.plugin.ops.register;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import patmob.data.ops.impl.register.RegisterRequestParams;

/**
 *
 * @author Piotr
 */
public class EPRegisterFrame extends javax.swing.JFrame {
    EPRegisterPlugin registerPlugin;
    String[] patentNumbers;

    /**
     * Creates new form EPRegisterFrame
     */
    public EPRegisterFrame() {
        initComponents();
    }

    public EPRegisterFrame(EPRegisterPlugin plugin) {
        this();
        registerPlugin = plugin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchQueryTextArea = new javax.swing.JTextArea();
        searchSampleResultButton = new javax.swing.JRadioButton();
        searchAllResultButton = new javax.swing.JRadioButton();
        searchAllResultField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        numbersFromUserRadioButton = new javax.swing.JRadioButton();
        numbersFromFileRadioButton = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        getDataTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        executeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("European Patent Register");
        setAutoRequestFocus(false);

        jSplitPane1.setDividerLocation(190);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel1.setText("Query");

        searchQueryTextArea.setColumns(20);
        searchQueryTextArea.setRows(2);
        jScrollPane2.setViewportView(searchQueryTextArea);

        buttonGroup3.add(searchSampleResultButton);
        searchSampleResultButton.setSelected(true);
        searchSampleResultButton.setText("Tree Sample");

        buttonGroup3.add(searchAllResultButton);
        searchAllResultButton.setText("Download All:");
        searchAllResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllResultButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Results");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchAllResultButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchAllResultField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchSampleResultButton)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchSampleResultButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAllResultButton)
                    .addComponent(searchAllResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Register", jPanel2);

        buttonGroup1.add(numbersFromUserRadioButton);
        numbersFromUserRadioButton.setSelected(true);
        numbersFromUserRadioButton.setText("Enter Publication Numbers");
        numbersFromUserRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersFromUserRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(numbersFromFileRadioButton);
        numbersFromFileRadioButton.setText("Get Numbers from File");
        numbersFromFileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersFromFileRadioButtonActionPerformed(evt);
            }
        });

        getDataTextArea.setColumns(20);
        getDataTextArea.setRows(2);
        jScrollPane3.setViewportView(getDataTextArea);

        jLabel3.setText("Results");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Log Sample Data");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Download All:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(numbersFromUserRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(numbersFromFileRadioButton))
                            .addComponent(jLabel3))
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbersFromUserRadioButton)
                    .addComponent(numbersFromFileRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Get Data for Publications", jPanel3);

        jSplitPane1.setLeftComponent(jTabbedPane1);

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        logTextArea.setText("LOG\n");
        jScrollPane1.setViewportView(logTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(executeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(executeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:
                //Search Register
                String query = searchQueryTextArea.getText();
                if (!query.equals("")) {
                    RegisterRequestParams searchParams = 
                            new RegisterRequestParams(query);
                    if (searchSampleResultButton.isSelected()) {
                        searchParams.setResultType(
                                RegisterRequestParams.SAMPLE_RESULT);
                    } else {
                        searchParams.setResultType(
                                RegisterRequestParams.ALL_RESULT);
                        searchParams.setFilePath(
                                searchAllResultField.getText());
                    }
                    
                    registerPlugin.submitSearchRequest(searchParams);
                    logTextArea.append("Submitting: " + query + "\n");
                    searchQueryTextArea.setText("");
                }
                break;
            case 1:
                //Get data
                if (numbersFromUserRadioButton.isSelected()) {
                    patentNumbers = getDataTextArea.getText().split("[ ,;]");
                }
                
                RegisterRequestParams searchParams = 
                        new RegisterRequestParams(patentNumbers);
                registerPlugin.submitBiblioRequest(searchParams);
//                for (String patent : patentNumbers) {
//                    System.out.println(patent);
//                }
//                logTextArea.append("Get data: " + getDataTextArea.getText() + "\n");
        }
    }//GEN-LAST:event_executeButtonActionPerformed

    private void searchAllResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllResultButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int i = fc.showSaveDialog(this);
        if (i==JFileChooser.APPROVE_OPTION) {
            File resultFile = fc.getSelectedFile();
            String path = resultFile.getAbsolutePath();
            searchAllResultField.setText(path);
        } else {
            searchSampleResultButton.setSelected(true);
        }
    }//GEN-LAST:event_searchAllResultButtonActionPerformed

    private void numbersFromFileRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersFromFileRadioButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);
        if (i==JFileChooser.APPROVE_OPTION) {
            getDataTextArea.setEditable(false);
            getDataTextArea.setText(getNumbersFromFile(fc.getSelectedFile()));
            //and store numbers in patentArrayList
        } else {
            numbersFromUserRadioButton.setSelected(true);
        }
    }//GEN-LAST:event_numbersFromFileRadioButtonActionPerformed

    private void numbersFromUserRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersFromUserRadioButtonActionPerformed
        getDataTextArea.setText("");
        getDataTextArea.setEditable(true);
    }//GEN-LAST:event_numbersFromUserRadioButtonActionPerformed

    private String getNumbersFromFile(File patentListFile) {
        ArrayList<String> patentArrayList = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(
                new FileReader(patentListFile))) {
            String line;
            while ((line=br.readLine())!=null) {
                if (line.contains(" ")) {
                    //skip kind code etc,
                    patentArrayList.add(line.substring(0, line.indexOf(" ")));
                } else {
                    patentArrayList.add(line);
                }
            }
            patentNumbers = patentArrayList.toArray(new String[0]);
        } catch (Exception x) {
            System.out.println("getNumbersFromFile: " + x);
        }
        return patentListFile.getAbsolutePath() + "\n" +
                patentArrayList.get(0) + "... and " + 
                (patentArrayList.size() - 1 ) + " more";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EPRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EPRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EPRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EPRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EPRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton executeButton;
    private javax.swing.JTextArea getDataTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JRadioButton numbersFromFileRadioButton;
    private javax.swing.JRadioButton numbersFromUserRadioButton;
    private javax.swing.JRadioButton searchAllResultButton;
    private javax.swing.JTextField searchAllResultField;
    private javax.swing.JTextArea searchQueryTextArea;
    private javax.swing.JRadioButton searchSampleResultButton;
    // End of variables declaration//GEN-END:variables
}
